var annotated_dup =
[
    [ "Action", "struct_action.html", "struct_action" ],
    [ "ActItem", "struct_act_item.html", "struct_act_item" ],
    [ "alloc_handle_t", "structalloc__handle__t.html", "structalloc__handle__t" ],
    [ "alloc_hdr_s", "structalloc__hdr__s.html", "structalloc__hdr__s" ],
    [ "alloc_root_s", "structalloc__root__s.html", "structalloc__root__s" ],
    [ "aRule", "structa_rule.html", "structa_rule" ],
    [ "Floatlist", "struct_floatlist.html", "struct_floatlist" ],
    [ "HTentryStruct", "struct_h_tentry_struct.html", "struct_h_tentry_struct" ],
    [ "IDstring", "struct_i_dstring.html", "struct_i_dstring" ],
    [ "Premise", "struct_premise.html", "struct_premise" ],
    [ "Sadjlist", "struct_sadjlist.html", "struct_sadjlist" ],
    [ "Scontrol", "struct_scontrol.html", "struct_scontrol" ],
    [ "Scoord", "struct_scoord.html", "struct_scoord" ],
    [ "Scurve", "struct_scurve.html", "struct_scurve" ],
    [ "Sdemand", "struct_sdemand.html", "struct_sdemand" ],
    [ "SField", "struct_s_field.html", "struct_s_field" ],
    [ "Slink", "struct_slink.html", "struct_slink" ],
    [ "Snode", "struct_snode.html", "struct_snode" ],
    [ "Spattern", "struct_spattern.html", "struct_spattern" ],
    [ "Spump", "struct_spump.html", "struct_spump" ],
    [ "Sseg", "struct_sseg.html", "struct_sseg" ],
    [ "Ssource", "struct_ssource.html", "struct_ssource" ],
    [ "Stank", "struct_stank.html", "struct_stank" ],
    [ "Svalve", "struct_svalve.html", "struct_svalve" ],
    [ "Tmplist", "struct_tmplist.html", "struct_tmplist" ]
];